// =============================================================================
// MechAfrica API - Main Export File
// =============================================================================

// Export the API client singleton and class
export { api, MechAfricaAPIClient } from "./client";

// Export all types
export type {
  // Backend types
  ApiResponse,
  BackendLoginRequest,
  BackendLoginResponse,
  BackendUser,
  BackendPaginatedUsers,
  BackendUserFilters,
  BackendDashboardData,
  BackendDashboardOverview,
  DataQualitySummary,
  ColumnMapping,
  ColumnAnalysisResult,
  BackendUserStats,
  BackendServiceStats,
  BackendRecentActivity,
  BackendTopRegion,
  BackendServiceRequest,
  BackendNotificationLog,
  BackendRequestStatus,
  BackendServiceRequestFarmer,
  BackendServiceRequestProvider,
  BackendPaginatedServiceRequests,
  BackendTrendsData,
  BackendTrendItem,
  BackendTrendsSummary,
  BackendPaymentSummary,
  BackendWeatherData,
  BackendCurrentWeather,
  BackendHourlyWeather,
  BackendDailyWeather,
  BackendDailyTemp,
  BackendWeatherCondition,
  BackendRegisterRequest,
  BackendManageUserRequest,
  BackendUpdateProfileRequest,
  AdminUpdateUserRequest,
  // Frontend types
  FrontendUser,
  FrontendLoginResponse,
  FrontendContact,
  FrontendContactsResponse,
  FrontendPagination,
  FrontendRequestItem,
  FrontendRequestsResponse,
  FrontendAdmin,
  FrontendAdminsResponse,
  FrontendFinanceSummaryItem,
  FrontendFinancesResponse,
  FrontendStatistics,
  FrontendStatisticsResponse,
  // Bulk Onboarding types
  OnboardJobStatus,
  ParticipantType,
  IssueType,
  OnboardEventType,
  RoleType,
  OnboardJobConfig,
  OnboardJobProgress,
  OnboardResultSummary,
  OnboardedRecord,
  SkippedRecord,
  ProblematicRecord,
  OnboardJobResult,
  BackendOnboardJob,
  FrontendOnboardJob,
  // New staging table types (Phase 3)
  OnboardStagedRecord,
  OnboardProblematicRecord,
  OnboardSkippedRecord,
  StagedRecordsPaginatedResponse,
  OnboardUploadResponseData,
  OnboardUploadResponse,
  OnboardListJobsResponseData,
  OnboardJobsListResponse,
  OnboardJobResponse,
  OnboardProgressResponseData,
  OnboardProgressResponse,
  OnboardedRecordsResponseData,
  OnboardedRecordsResponse,
  SkippedRecordsResponseData,
  SkippedRecordsResponse,
  ProblematicRecordsResponseData,
  ProblematicRecordsResponse,
  OnboardConfirmResponseData,
  OnboardConfirmResponse,
  OnboardCancelResponseData,
  OnboardCancelResponse,
  OnboardProgressPayload,
  OnboardWebSocketMessage,
  OnboardRecordsPagination,
  // New types for retry, skip, delete operations
  RetryResult,
  BulkRetryResult,
  UpdateRecordRequest,
  UpdateRecordResponse,
  BulkRetryRequest,
  BulkRetryResponse,
  SkipRecordRequest,
  SkipDeleteResponse,
  EditedCountResponse,
  RetryRecordResponse,
  OnboardSummaryResponseData,
  OnboardSummaryResponse,
  OnboardResultResponseData,
  OnboardResultResponse,
  EditableRecord,
} from "./types";

// Export constants and helper functions
export {
  ONBOARD_ENDPOINTS,
  STATUS_CONFIG,
  ISSUE_TYPE_CONFIG,
  PARTICIPANT_TYPE_CONFIG,
  isRecordEdited,
  getRecordEditedAt,
  getEditedRecords,
  getRowNumbers,
  groupRetryResults,
} from "./types";

// Export all transformers
export {
  // Utility functions
  formatDate,
  formatISODate,
  generateInitials,
  mapRoleToType,
  mapTypeToRole,
  mapRequestStatus,
  mapStatusToBackend,
  formatCurrency,
  calculateDemandSupplyRatio,
  // Response transformers
  transformLoginResponse,
  transformBackendUser,
  transformUserToContact,
  transformUsersToContacts,
  transformServiceRequest,
  transformServiceRequests,
  transformUserToAdmin,
  transformUsersToAdmins,
  transformPaymentSummary,
  transformDashboardToStatistics,
  // Request transformers
  transformContactToBackendUser,
  transformAdminToBackendUser,
} from "./transformers";
